sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: 1+nNPHw2eFU+W9KfDFB22mXzl1KpK6Ya+5BgMPIUlCDYGd+FQZgA22o/fI1dTg+riM13tyv8J0xf/wOy5TBRdx8BwvOCLPUu+cIaRAtkAxclh+oYpFoDjo+sWbkPsAKMobsd1cwEs4R6UBGsgpwGMG6JnDpIipxGN3QGHfLAta8NA/s3XMU4PAl+vac5DG6OFnK8N4cCr5XkvFh6GnPgq5i4OunJ23t2ZhYFJVvmODX8GM9VfEkIAKEPxn0JQqkTivxsWh4uT71aunxerpXJZ5Tsv+2QCrZYcy5iGkjTHjsyDxSnAyAPCTPSKPjF2zw33fSy4m4jLL+RueFnHTvLCbN1qp3ZupeTlQzNat9jBJ89bfcUfZ/StWZVOHld6TZaN6oo8KlJTd4ftPaQkJBvUbSUHy+MyD2bBUpleKkBPNLKSbsijkKRc7H3owlY6qVskrbhLNqRG8rUlNd+ZmpPAtrCkcUOxoa8hki5OV7SdArLzXnVv2c5D095Nja1HU10cLN78rkRBjDJxubY8V8WOz6SVxLfgEFJ3SPfqAmFaepUUDViwsTQIorer4Kr5tuNkJaHPNHLiK1AZ6Bf89xCIOPXadANlMFvXDLOv6Yku+3hOYb9FW9qvLQEqz2UPqPS7Zx1pqVJu/EOXkhLCfIFT9OabQPeVj+WiRQ5yLW/b2k=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Wildfire_2066
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy